version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    volumes:
      - ./frontend:/app
    working_dir: /app

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    command: ["python", "wsgi.py"]
    volumes:
      - ./backend:/app
    working_dir: /app