version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3010:3000"
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    command: ["python", "/app/wsgi.py"]
    volumes:
      - ./backend:/app